### ISSUE TITLE
Failed on " HopperEnv' object has no attribute 'seed' "

### ISSUE THREAD

**Issue by HughesField** [Khrylx/PyTorch-RL#37]
Traceback (most recent call last):
  File "/home/zjt/exp/PyTorch-RL/examples/ppo_gym.py", line 70, in <module>
    env.seed(args.seed)
  File "/home/zjt/anaconda3/envs/mujoco/lib/python3.9/site-packages/gym/core.py", line 241, in __getattr__
    return getattr(self.env, name)
  File "/home/zjt/anaconda3/envs/mujoco/lib/python3.9/site-packages/gym/core.py", line 241, in __getattr__
    return getattr(self.env, name)
  File "/home/zjt/anaconda3/envs/mujoco/lib/python3.9/site-packages/gym/core.py", line 241, in __getattr__
    return getattr(self.env, name)
AttributeError: 'HopperEnv' object has no attribute 'seed'

When "python examples/ppo_gym.py --env-name Hopper-v2", the program encountered an error with env.seed(args.seed), and even after commenting out this line, it ran into another error related to 'seed': AttributeError: 'numpy.random._generator.Generator' object has no attribute 'seed'.

**Comment by zhangzadou** [comment]
use "env.reset(seed=args.seed)"
